config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  get '/home/about_us'

  resources :ideas, only: [:show, :new, :create, :index] do
    resources :proposals, only: [:new, :create]
    member do
      post 'favorite'
      post 'unfavorite'
    end
  end

  resources :investors, only: [:index, :show]
  resources :invites, only: [:new, :create, :show]
  resources :favorite_ideas, only: [:index]
  resources :proposals, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ideas, dependent: :destroy
end

app/models/favorite_idea.rb
class FavoriteIdea < ApplicationRecord
  belongs_to :user
  belongs_to :idea
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, :description, :estimated_project_time,
            :initial_investment_value, :estimated_time_to_profit, presence: true
  belongs_to :user
  belongs_to :category

  has_many :proposals, dependent: :nullify
  has_many :investors, dependent: :nullify

  def proposal_from(user)
    proposals.find_by(user: user)
  end
  # proposta de uma idea especifica de um usuario
  has_many :favorite_ideas, dependent: :destroy

  def favorite?(user)
    favorite_ideas.where(user: user, active: true).any?
  end
end

app/models/investment_type.rb
class InvestmentType < ApplicationRecord
  has_many :proposals, dependent: :nullify
end

app/models/invite.rb
class Invite < ApplicationRecord
  validates :name, :linkedin, :email, presence: true
  validates :email,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on:
            :create, message: 'Email inválido' }
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :investment_type
  belongs_to :idea
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :ideas, dependent: :nullify
  has_many :proposals, dependent: :nullify
  has_many :favorite_ideas, dependent: :destroy

  attr_accessor :user_type

  validates :name, :document, :linkedin, :birth_day, presence: true
  validate :check_amount
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def check_amount
    return unless user_type == 'investor' && amount_available_to_invest.blank?

    errors[:amount_available_to_invest] << 'não pode ficar em branco'
  end

  def investor?
    amount_available_to_invest
  end

  def idealizer?
    !investor?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: %i[name document linkedin
                         birth_day
                         amount_available_to_invest
                         user_type]
    )
  end
end

app/controllers/favorite_ideas_controller.rb
class FavoriteIdeasController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.investor?
      @fav_ideas = current_user.favorite_ideas.where(active: true)
    else
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about_us; end

  def index
    if user_signed_in? && current_user.investor?
      @ideas = Idea.all
    elsif user_signed_in? && current_user.idealizer?
      @ideas = current_user.ideas
      redirect_to ideas_path
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :check_investor, only: %i[index new]

  def index
    @ideas = current_user.ideas
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user

    if @idea.save
      flash[:notice] = 'Sua ideia foi criada com sucesso!'
      redirect_to @idea
    else
      flash[:alert] = 'Preencha todos os campos!'
      render 'new'
    end
  end

  def show
    @idea = Idea.find(params[:id])
    @proposal = @idea.proposal_from(current_user)
  end

  def favorite
    @idea = Idea.find(params[:id])
    @favorite_idea = FavoriteIdea.new(idea: @idea, user: current_user)
    @favorite_idea.save
    redirect_to idea_path(@idea)
  end

  def unfavorite
    @idea = Idea.find(params[:id])
    @favorite_idea = @idea.favorite_ideas.find_by(user: current_user,
                                                  active: true)
    @favorite_idea.active = false
    @favorite_idea.save
    redirect_to idea_path(@idea)
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description, :estimated_project_time,
                                 :initial_investment_value,
                                 :estimated_time_to_profit,
                                 :category_id)
  end

  def check_investor
    redirect_to root_path if !current_user || current_user.investor?
  end
end

app/controllers/investors_controller.rb
class InvestorsController < ApplicationController
  before_action :authenticate_user!

  def index
    @investors = User.where.not(amount_available_to_invest: nil,
                                id: current_user)
  end

  def show
    @investor = User.find(params[:id])
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!
  def new
    @invite = Invite.new
  end

  def create
    @invite = Invite.new(params.require(:invite).permit(:name,
                                                        :linkedin, :email))

    if @invite.save
      flash[:notice] = "Obrigado por indicar um investidor \
para nossa plataforma"
      redirect_to @invite
    else
      render 'new'
    end
  end

  def show
    @invite = Invite.find(params[:id])
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_user!

  def index
    return @proposals = current_user.proposals if current_user.investor?

    @proposals = Proposal.where(idea: current_user.ideas)
  end

  def new
    @idea = Idea.find(params[:idea_id])
    @proposal = Proposal.new
  end

  def create
    @idea = Idea.find(params[:idea_id])
    @proposal = @idea.proposals.new(proposal_params)
    if @proposal.save
      ProposalMailer.notify_idealizer(@idea.id, @proposal.id)
      redirect_to @idea
    else
      render 'new'
    end
  end

  private

  def proposal_params
    params.require(:proposal).permit(:investment_type_id, :doubts, :details)
          .merge(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    'active' if current_page? path
  end
end

app/views/favorite_ideas/index.html.erb
<div class="container">
  <h1>Ideias Favoritas</h1>

  <div class="row">
    <% @fav_ideas.each do |fav| %>
      <div class="col-md-4">
        <div id="idea-<%= fav.idea.id %>">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= fav.idea.title %></h5>

            <p><%if fav.idea.favorite?(current_user)%>
            <%= image_tag 'favorite_heart', size: "32x32" %>
          <% end %></p>
            <p class="card-text"><%= truncate(fav.idea.description, length: 25)%></p>
            <p class="card-text"><%= fav.idea.category.name %></p>
            <p><%= link_to('Ver detalhes', fav.idea, class: 'btn btn-primary') %> </p>

          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>Valor inicial do investimento: </strong> <%= number_to_currency(fav.idea.initial_investment_value) %></li>
            <li class="list-group-item"><strong>Tempo estimado do projeto: </strong><%= t('months', count: fav.idea.estimated_project_time) %></li>
            <li class="list-group-item"><strong>Tempo estimado para retorno: </strong><%= t('months', count: fav.idea.estimated_time_to_profit) %></li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <%if @fav_ideas.empty?%>
    <div class="alert alert-warning" role="alert">
      Você ainda não possui nenhuma ideia favorita
    </div>
  <%end%>
</div>

app/views/home/_carousel.html.erb
<div>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag('slide1.jpg', style:"width:100%;", class: 'carousel-image') %>
        <div class="container">
          <div class="carousel-caption d-none d-md-block text-center opac">
            <h1>Start to Business.</h1>
            <p>Encontre investidores dispostos a firmar parceria.</p>
            <p><%= link_to 'Detalhes', home_about_us_path, class:'btn btn-lg btn-primary', role:'button' %></p>
          </div>
        </div>

      </div>
      <div class="carousel-item">
        <%= image_tag('slide2.jpg', style:"width:100%;") %>
        <div class="container">
          <div class="carousel-caption d-none d-md-block text-lecenterft opac">
            <h1>Está afim de investir?</h1>
            <p>Este site te ajudará a encontrar a ideia adequatada para você lucrar muito!</p>
            <p><%= link_to 'Seja um investidor', new_user_registration_path, class:'btn btn-lg btn-primary', role:'button' %></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag('slide3.jpg', style:"width:100%;") %>
        <div class="container">
          <div class="carousel-caption d-none d-md-block text-center opac">
            <h1>Possui uma ideia?</h1>
            <p>Interaja com investidores, envie suas ideis e muito mais!</p>
            <p><p><%= link_to 'Seja um idealizador', new_user_registration_path, class:'btn btn-lg btn-primary', role:'button' %></p></p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/home/_quotes.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="text-center">
      <h2>O que dizem de nós</h2>
    </div>
  </div>
</div>

<div class="container marketing">
  <hr class="featurette-divider">

  <div class="row">
    <div class="col-lg-4">
      <div class="text-center">
        <%= image_tag 'people1.jpg', class: 'rounded-circle', width: '140', height: '140' %>
        <blockquote>
          Nunca foi tão fácil ter contato com tantas empresas
          <cite>Fulano</cite>
        </blockquote>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="text-center">
        <%= image_tag 'people2.jpg', class: 'rounded-circle', width: '140', height: '140' %>
        <blockquote>
          Era difícil achar investimentos agora tudo ficou mais fácil
          <cite>Sicrano</cite>
        </blockquote>
        <!--<p><a class="btn btn-secondary" href="#" role="button">Ver detalhes »</a></p>-->
      </div>
    </div>
    <div class="col-lg-4">
      <div class="text-center">
        <%= image_tag 'people3.jpg', class: 'rounded-circle', width: '140', height: '140' %>
        <blockquote>
          O Melhor lugar para achar empresas para investir
          <cite>Beltrano</cite>
        </blockquote>
        <!--<p><a class="btn btn-secondary" href="#" role="button">Ver detalhes »</a></p>-->
      </div>
    </div>
  </div>

  <hr class="featurette-divider">
</div>

app/views/home/about_us.html.erb
<div class="container">

      <!-- Introduction Row -->
      <h1 class="my-4">Sobre nós
        
      </h1>
      <p>
      O time de desenvolvimento teve a brilhante ideia de juntar o útil ao agradável, quando uma pessoa precisa 
      de um investidor para a sua ideia, raramente consegue um investidor e o investidor também possui dificuldade de encontrar pessoas criativas,
      poreḿ essa dificuldade acabou, na nossa plataforma você pode ser os dois!
      </p>

      <!-- Team Members Row -->
      <div class="row">
        <div class="col-lg-12">
          <h2 class="my-4">Nosso time</h2>
        </div>
        <div class="col-lg-3 col-sm-6 text-center mb-4">
        <%= image_tag('reynaldo.png', :size => "200x200", class:'rounded-circle img-fluid d-block mx-auto') %> 
        <!--<img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">-->
          <h3>Reynaldo
            <small>Product Owner</small>
          </h3>
          <p>Dono do produto e desenvolvedor</p>
        </div>
        <div class="col-lg-3 col-sm-6 text-center mb-4">
        <%= image_tag('carla.jpg', :size => "200x200", class:'rounded-circle img-fluid d-block mx-auto') %> 
          <!--<img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">-->
          <h3>Carla
            <small>Dev</small>
          </h3>
          <p>Atua como desenvolvedora desde 2010, além de desenvolvedora trabalhou como analista de qualidade de software</p>
        </div>
        <div class="col-lg-3 col-sm-6 text-center mb-4">
          <%= image_tag('simone.png', :size => "200x200", class:'rounded-circle img-fluid d-block mx-auto') %> 
          <!--<img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">-->
          <h3>Simone
            <small>Dev</small>
          </h3>
          <p>Trabalhou como analisata de qualidade de software e atualmente desenvolve para a S2B</p>
        </div>
        <div class="col-lg-3 col-sm-6 text-center mb-4">
        <%= image_tag('willian.jpg', :size => "200x200", class:'rounded-circle img-fluid d-block mx-auto') %>
          <!--<img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">-->
          <h3>Willian
            <small>Dev</small>
          </h3>
          <p>Trabalhou  como administrador de sistemas  e atualmente desenvolve para a S2B</p>
        </div>
      </div>

    </div>

app/views/home/index.html.erb
<% unless user_signed_in? %>
  <%= render partial: 'carousel' %>
  <%= render partial: 'quotes' %>
<% end %>


<div class="container-fluid">
  <div class="row justify-content-center">
    <% if user_signed_in? %>
      <% @ideas.each do |idea|%>
        <div id="idea-<%=idea.id%>">
          <div class="col6 ml-2 mr-2 mb-2">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= idea.title %></h5>

                <p><%if idea.favorite?(current_user)%>
                <%= image_tag 'favorite_heart', size: "32x32" %>
              <% end %></p>
                <p class="card-text"><%= truncate(idea.description, length: 25)%></p>
                <p class="card-text"><%= idea.category.name %></p>
                <p><%= link_to('Ver detalhes', idea, class: 'btn btn-primary') %> </p>

              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Valor inicial do investimento: </strong> <%= number_to_currency(idea.initial_investment_value) %></li>
                <li class="list-group-item"><strong>Tempo estimado do projeto: </strong><%= t('months', count: idea.estimated_project_time) %></li>
                <li class="list-group-item"><strong>Tempo estimado para retorno: </strong><%= t('months', count: idea.estimated_time_to_profit) %></li>
              </ul>
            </div>
          </div>
        </div>
      <% end%>
    <% end %>
  </div>
</div>

app/views/ideas/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="mt-5 mb-4">
      <h2 class="mb-4">Minhas Ideias</h2>
    </div>
  </div>
</div>

<% if @ideas.empty? %>
  <div class="alert alert-warning" role="alert">
    Não há ideias cadastradas
  </div>
<% end %>

<div class="container-fluid">
  <div class="row justify-content-center">
    <% @ideas.each do |idea| %>
      <div class="col-sm-3 mb-4">
        <div id="idea-<%=idea.id%>">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= idea.title %></h5>
              <p><%if idea.favorite?(current_user)%>
              <%= image_tag 'favorite_heart', size: "32x32" %>
            <% end %></p>
              <p class="card-text"><%= idea.description %></p>
              <p class="card-text"><%= idea.category.name %></p>
              <p><%= link_to('Ver detalhes', idea) %> </p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Tempo estimado: </strong><%= t('months', count: idea.estimated_project_time) %> </li>
              <li class="list-group-item"><strong>Valor inicial do investimento: </strong> <%= number_to_currency(idea.initial_investment_value) %> </li>
              <li class="list-group-item"><strong>Tempo estimado para retorno: </strong><%= t('months', count: idea.estimated_time_to_profit) %> </li>
              <li class="list-group-item"><strong>Idealizador: </strong><%= idea.user.name %></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/ideas/new.html.erb
<div class="container col-sm-6 mt-5">
  <h2 class="">Tenho uma ideia</h2>
  <%= simple_form_for @idea do |f| %>
    <%= f.input :title, label: 'Título' %>
    <%= f.input :description, label: 'Descrição',as: :text %>
    <%= f.association :category, label: 'Categoria' %>
    <%= f.input :estimated_project_time, label: 'Tempo estimado de projeto' %>
    <%= f.input :initial_investment_value, label: 'Valor inicial do investimento' %>
    <%= f.input :estimated_time_to_profit, label: 'Tempo estimado para retorno' %>
    <div class="form-actions">
      <%= f.button :submit , 'Enviar Ideia', class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/ideas/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 mt-4 mb-4">
      <h1 class="mb-4"><%= @idea.title %></h1>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @idea.title %></h5>
          <p class="card-text"><%= @idea.description %></p>
          <p class="card-text"><%= @idea.category.name %></p>
        <%if !@idea.favorite?(current_user)%>
          <%= link_to favorite_idea_path(@idea), class: 'favorite-button', method: :post do %>
            <%= image_tag 'unfavorite_heart', size: "32x32"%>
          <% end %>
        <% else %>
            <%= link_to unfavorite_idea_path(@idea), class: 'unfavorite-button', method: :post do %>
              <%= image_tag 'favorite_heart', size: "32x32" %>
            <% end %>
        <% end %>

        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Tempo estimado: </strong><%= t('months', count: @idea.estimated_project_time) %></li>
          <li class="list-group-item"><strong>Valor inicial do investimento: </strong> <%= number_to_currency @idea.initial_investment_value %> </li>
          <li class="list-group-item"><strong>Tempo estimado para retorno: </strong><p><%= t('months', count: @idea.estimated_time_to_profit) %></p></li>
        </ul>
        <% if @proposal.nil? && current_user.investor?  %>
          <div class="card-body">
            <a href="<%= new_idea_proposal_path(idea_id: @idea) %>" class="card-link">Deseja investir nessa ideia?</a>
          </div>
        <% end %>
        <% if current_user && @idea.user.eql?(current_user)  %>
        <div class="card-body">
          <a href="#" class="card-link">Editar</a>
        </div>
      <% end %>
      </div>
    </div>
  </div>

  <% if @proposal %>
    <hr>
    <h2 class="text-center">Proposta Enviada</h2>
    <div class="container-fluid mt-5">
      <div class="row justify-content-center">
        <div class="col-sm-4">
          <div class="card">
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Nome: </strong><%= current_user.name %></li>
              <li class="list-group-item"><strong>Tipo de investimento: </strong> <%= @proposal.investment_type.name %> </li>
              <li class="list-group-item"><strong>Dúvidas: </strong><%= @proposal.doubts %></li>
              <li class="list-group-item"><strong>Fale mais sobre sua proposta: </strong><%= @proposal.details %></li>
            </ul>
            <div class="card-body">
              <a href="#" class="card-link">Editar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/investors/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 mt-4 mb-4">
      <h2 class="mb-4">Investidores</h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @investors.each do |investor| %>
      <div class="col-sm-6 mb-5">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to(investor.name, investor_path(investor)) %></h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>e-mail: </strong><%= investor.email %></li>
            <li class="list-group-item"><strong>Valor disponível para investir: </strong> <%= number_to_currency investor.amount_available_to_invest %> </li>
          </ul>
          <div class="card-body">
            <a href="<%= investor_path(investor) %>" class="btn btn-primary">Ver perfil</a>
            <a href="#" class="btn btn-secondary">Enviar mensagem</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/investors/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 mt-4 mb-4">
      <h2 class="mb-4"><%= @investor.name %></h2>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>e-mail: </strong><%= @investor.email %></li>
          <li class="list-group-item"><strong>Valor disponível para investir: </strong> R$ <%= number_to_currency @investor.amount_available_to_invest %> </li>
          <li class="list-group-item"><strong>Data de Nascimento: </strong><%= localize(@investor.birth_day) %> </li>
        </ul>
        <div class="card-body">
          <a href="#" class="btn btn-primary">Enviar mensagem</a>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'Voltar', investors_path, class: 'btn btn-secondary mt-2' %>
</div>

app/views/invites/new.html.erb
<div class="container col-sm-8 mt-4 mb-4">
  <h2>Indicar Investidor</h2>
</div>

<div class="container col-sm-8 mt-4 mb-4">
  <%= simple_form_for(@invite) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs form-group col-sm-12 mt-4 mb-4">
      <%= f.input :name,
                  label: 'Nome',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" }%>
      <%= f.input :linkedin,
                  label: 'Linkedin',
                  required: true,
                  input_html: { autocomplete: "linkedin" }%>
      <%= f.input :email,
                  label: 'Email',
                  required: true,
                  input_html: { autocomplete: "email" }%>
    </div>

    <div class="form-inputs form-group col-sm-8 mt-4 mb-4">
      <%= f.button :submit, "Enviar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/invites/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 mt-4 mb-4">
      <h2 class="mb-4">Sua Indicação</h2>
    </div>
  </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><strong>Investidor indicado: </strong><%= @invite.name %></li>
                    <li class="list-group-item"><strong>Email: </strong><%= @invite.email %> </li>
                    <li class="list-group-item"><strong>Linkedin: </strong><%= @invite.linkedin %> </li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/proposals/new.html.erb
<div class="container col-sm-8 mt-4 mb-4">
  <h2>Proposta de Investimento</h2>
</div>

<div class="container col-sm-8 mt-4 mb-4">
  <%= simple_form_for([@idea, @proposal]) do |f| %>

    <div class="form-inputs form-group col-sm-12 mt-4 mb-4">
      <%= f.association :investment_type %>
      <%= f.input :doubts %>
      <%= f.input :details %>
      <%= f.button :submit, 'Enviar', class: "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', class: 'logo' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="navbar-item">
          <%= link_to 'Home', root_path, class: "nav-link #{active? root_path}" %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.idealizer? %>
            <li class="navbar-item">
              <%= link_to 'Tenho uma Ideia', new_idea_path, class: "nav-link #{active? new_idea_path}" %>
            </li>
            <li class="navbar-item">
              <%= link_to 'Minhas ideias', ideas_path, class: "nav-link #{active? ideas_path}" %>
            </li>
          <% end %>
          <li class="navbar-item">
            <%= link_to 'Indique um investidor', new_invite_path, class: "nav-link #{active? new_invite_path}" %>
          </li>
          <% if current_user.investor? %>
            <li class="navbar-item">
              <%= link_to 'Favoritas', favorite_ideas_path, class: "nav-link #{active? favorite_ideas_path}" %>
            </li>
          <% end %>
          <ul class="nav navbar-nav justify-content-end">
            <li class="nav-item">
              <%= link_to 'Encontre um investidor', investors_path, class: "nav-link #{active? investors_path}" %>
            </li>
          </ul>
          <li class="navbar-item">
            <%= link_to 'Minhas propostas', proposals_path, class: "nav-link #{active? proposals_path}" %>
          </li>
        <% end %>
      </ul>
    </div>
    <div id="navbarSupportedContent">
      <ul class="nav navbar-nav justify-content-end">
        <% if user_signed_in? %>
          <li class="navbar-item">
            <%= link_to('Logout', destroy_user_session_path, method:'delete', class: 'nav-link') if user_signed_in?%>
          </li>
        <% else %>
          <li class="navbar-item">
            <%= link_to 'Cadastre-se', new_user_registration_path, class: "nav-link #{active? new_user_registration_path}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logar', user_session_path, class: "nav-link #{active? user_session_path}" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>